<?php

namespace RzlApp\Ziggy\Output;

use Stringable;
use RzlApp\Ziggy\Ziggy;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Support\Collection;

class Types implements Stringable
{
  public function __construct(protected Ziggy $ziggy) {}

  public function __toString(): string
  {
    $routes = $this->routes();

    return <<<JAVASCRIPT
/* eslint-disable no-unused-vars */
/* This file is generated by Rzl Ziggy (Custom) Libs. */
declare module "rzl-ziggy" {
interface RouteList {$routes->toJson(JSON_PRETTY_PRINT)}
}
export {};

JAVASCRIPT;
  }

  protected function routes(): Collection
  {
    return collect($this->ziggy->toArray()['routes'])->map(function ($route) {
      return collect($route['parameters'] ?? [])->map(function ($param) use ($route) {
        return Arr::has($route, "bindings.{$param}")
          ? ['name' => $param, 'required' => ! Str::contains($route['uri'], "{$param}?"), 'binding' => $route['bindings'][$param]]
          : ['name' => $param, 'required' => ! Str::contains($route['uri'], "{$param}?")];
      });
    });
  }
}
